version: "3.9"
services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
  rails_api:
    build:
      context: .
      dockerfile: .docker/rails_api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./rails_api:/rails_api
    ports:
      - "3001:3001"
    depends_on:
      - postgres
